name: Add changeset to Renovate updates

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  call:
    uses: portabletext/.github/.github/workflows/renovate.yml@main
    secrets: inherit
